name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      xy_env:
          type: choice
          description: Xygeni environment
          options: 
          - DEMO_LGV
          - DEMO_LGVTRIAL
          - PRO_LGV
          - PRO_LGVTRIAL
          default: DEMO_LGVTRIAL
      action:
          type: choice
          description: Action
          options: 
          - Scan
          - Upload
          default: Scan
      loops:
        description: 'Number of uploads'
        default: "3"
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

env:

  FILE_SCAN: "xygeni-labdev-tuneado.yml"
  FILE_UPLOAD: "DownloadAndRun.yml"
  TEST_S: ""
  REPO_LIST: ("Mindustry" "graylog2-server" "dependency-track")
  XY_ENV: ${{ github.event.inputs.xy_env }}

  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
      
      - name: Set Xygeni env 
        run: |
            case "$XY_ENV" in 
            PRO_LGV)
              echo "PRO_LGV"
              echo XY_TOKEN=${{ secrets.XYGENI_TOKEN_PROLGV }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XYGENI_URL_PRO }} >> $GITHUB_ENV
              ;;
            PRO_LGVTRIAL)
              echo "PRO_LGVTRIAL"
              echo XY_TOKEN=${{ secrets.XYGENI_TOKEN_PRO_LGVTRIAL }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XYGENI_URL_PRO }} >> $GITHUB_ENV
              ;;
            DEMO_LGV)
              echo "DEMO_LGV"
              echo XY_TOKEN=${{ secrets.XYGENI_TOKEN_DEMO_LGV }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XYGENI_URL_DEMO }} >> $GITHUB_ENV
              ;;
            DEMO_LGVTRIAL)
              echo "DEMO_LGVTRIAL"
              echo XY_TOKEN=${{ secrets.XYGENI_TOKEN_DEMO_LGVTRIAL }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XYGENI_URL_DEMO }} >> $GITHUB_ENV
              ;;
            *)
              echo "DEFAULT (DEMO_LGVTRIAL)"
              echo XY_TOKEN=${{ secrets.XYGENI_TOKEN_DEMO_LGVTRIAL }} >> $GITHUB_ENV
              echo XY_URL=${{ secrets.XYGENI_URL_DEMO }} >> $GITHUB_ENV
              ;;
            esac
            


      - name: Create fork
        if: ${{ github.event.inputs.action }} == "pepe"
        run: | 
            echo sdlfjlsdjflsjfldsjflsd
            exit 1
            
            readarray repolist < repos.txt
            for line in "${repolist[@]}"
            do
                echo Creating fork for $line
                REPO_URL=$line
                # extract the protocol
                proto="$(echo $REPO_URL | grep :// | sed -e's,^\(.*://\).*,\1,g')"
                echo proto : $proto
                # remove the protocol
                url="$(echo ${REPO_URL/$proto/})"
                echo url : $url
                # extract the user (if any)
                user="$(echo $url | grep @ | cut -d@ -f1)"
                echo user : $user
                # extract the host and port
                hostport="$(echo ${url/$user@/} | cut -d/ -f1)"
                echo hostport : $hostport
                # by request host without port
                host="$(echo $hostport | sed -e 's,:.*,,g')"
                echo host : $host
                # by request - try to extract the port
                port="$(echo $hostport | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
                echo port : $port
                # extract the path (if any)
                path="$(echo $url | grep / | cut -d/ -f2-)"
                echo path : $path
                org="$(echo $path | grep / | cut -d/ -f1)"
                echo org : $org
                repo="$(echo $path | grep / | cut -d/ -f2-)"
                echo repo : $repo

                curl -Lb \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.PAT_FOR_XYGENI_SCAN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/$org/$repo/forks \
                      -d '{"organization":"LGVExternalRepos","name":"insecure-kubernetes-deployments","default_branch_only":true}'
            done
            
      - name: Copying Scan file
        run: | 
            exit 1
            readarray repolist < repos.txt
            for line in "${repolist[@]}"
            do
                echo Copying Scan file for $line
                chmod +x ./copy_to_repo.sh
                ./copy_to_repo.sh "$line" "${{ env.FILE_SCAN }}" "${{ secrets.PAT_FOR_XYGENI_SCAN }}" "${{ env.TEST_S }}"
              
            done



      - name: Copying Upload file
        run: | 
                
                readarray repolist < repos.txt
                for line in "${repolist[@]}"
                do
                    echo Copying Upload file for $line

                    chmod +x ./copy_to_repo.sh
                    ./copy_to_repo.sh "$line" "${{ env.FILE_UPLOAD }}" "${{ secrets.PAT_FOR_XYGENI_SCAN }}" "${{ env.TEST_S }}"
                  
                done
            
        
      - name: Trigger Workflow in Another Repository
        run: |

            readarray repolist < repos.txt
            for line in "${repolist[@]}"
            do
                echo Triggering Workflow for $line
                repo_owner="LGVExternalRepos" 
                chmod +x ./trigger_workflow.sh
                echo secrets.XY_URL_DEMO ${{ secrets.XY_URL_DEMO }} 
                echo XY_URL "$XY_URL"
                #./trigger_workflow.sh "$line" "$repo_owner" "${{ secrets.PAT_FOR_XYGENI_SCAN }}" "${{ github.event.inputs.loops }}" "${{ github.event.inputs.action }}"
                ./trigger_workflow.sh "$line" "$repo_owner" "${{ secrets.PAT_FOR_XYGENI_SCAN }}" "$XY_TOKEN" "$XY_URL" "${{ github.event.inputs.loops }}" "${{ github.event.inputs.action }}"
                    
            done
      
    

